using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SP.Parking.Terminal.Core.Models
{
    /// <summary>
    /// Terminal status
    /// </summary>
    public enum TerminalStatus
    {
        Disable = 0,
        Enable = 1
    }

    public class TerminalGroup
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    /// <summary>
    /// Terminal model
    /// </summary>
    public class Terminal
    {
        /// <summary>
        /// Gets or sets the identifier of terminal generated by server
        /// </summary>
        [JsonProperty("id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the identifier string of host known from client
        /// </summary>
        //private string _terminalId;
        [JsonProperty("terminal_id")]
        public string TerminalId { get; set; }

        /// <summary>
        /// Gets or sets the name of terminal
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the status of terminal
        /// </summary>
        [JsonProperty("status")]
        public TerminalStatus Status { get; set; }

        /// <summary>
        /// Gets or sets the IP address of terminal
        /// </summary>
        [JsonProperty("ip")]
        public string Ip { get; set; }

        /// <summary>
        /// Gets or set the flag indicates if terminal is timeout
        /// </summary>
        [JsonProperty("timeout")]
        public bool TimeOut { get; set; }

        //public override bool Equals(object obj)
        //{
        //    Terminal t = (Terminal)obj;
        //    if (this.Id == t.Id && this.Ip.Equals(t.Ip) && this.Name.Equals(t.Name)
        //        && this.TerminalId.Equals(t.TerminalId) && this.TimeOut == t.TimeOut && this.Status == t.Status)
        //    {
        //        return true;
        //    }
        //    else
        //        return false;
        //}
    }
}
